# Site settings
course_name: Natural Language Processing
course_description: "This unit provides students with a deep understanding of the basic theories and techniques used to process large-scale of text document data to understand, search, identify, and extract information from semi-structured text documents. The unit will cover basic technologies for text document analysis, including information retrieval, search and indexing, information extraction, document classification, and natural language understanding."
course_semester: "Winter 2024"

baseurl: "/SIT770-330" # the subpath of your site, e.g. /blog/
url: "http://rbouadjenek.github.io/" # the base hostname & protocol for your site

schoolname: "Deakin University"
schoolurl: "https://www.deakin.edu.au/"
# twitter_username: username 

address: |
    School of Information Technology
    Deakin University
    Victoria, Australia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
